<?php
// app/Providers/CustomUserProvider.php

namespace App\Providers;

use Illuminate\Contracts\Auth\UserProvider;
use Illuminate\Contracts\Auth\Authenticatable as UserContract;
use App\Models\CustomUser;

class CustomUserProvider implements UserProvider
{
    protected $users = [
        [
            'id' => 1,
            'username' => 'admin',
            'password' => 'Nusantara@1',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => true,
            'aset' => true,
            'finansial' => true,
            'hr'=>true,
            'sales'=>true,
            'legal'=>true,
            'progress'=>true,
            'pengadaan'=>true,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 2,
            'username' => 'superadmin',
            'password' => 'Nusantara1@!',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => true,
            'aset' => true,
            'finansial' => true,
            'hr'=>true,
            'sales'=>true,
            'legal'=>true,
            'progress'=>true,
            'pengadaan'=>true,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 3,
            'username' => 'mrc',
            'password' => 'Nusantara@1',
            'mrc' => true,
            'gis' => false,
            'lm' => true,
            'aigr1' => false,
            'garda' => false,
            'operasional' => false,
            'aset' => false,
            'finansial' => false,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>false,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 4,
            'username' => 'dksk',
            'password' => 'dksk@4121',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => true,
            'aset' => true,
            'finansial' => false,
            'hr'=>false,
            'sales'=>true,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 5,
            'username' => 'dkat',
            'password' => 'dkat@5234',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => true,
            'aset' => true,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 6,
            'username' => 'dpsb',
            'password' => 'dpsb@6452',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>true,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 7,
            'username' => 'dmas1',
            'password' => 'dmas1@7865',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => true,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 8,
            'username' => 'dmas2',
            'password' => 'dmas2@8965',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => true,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 9,
            'username' => 'dpak',
            'password' => 'dpak@9012',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 10,
            'username' => 'dpaj',
            'password' => 'dpaj@10112',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 11,
            'username' => 'dmrs',
            'password' => 'dmrs@11546',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 12,
            'username' => 'dmps',
            'password' => 'dmps@12657',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 13,
            'username' => 'dhkm',
            'password' => 'dhkm@13567',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => true,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>true,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 14,
            'username' => 'dpti',
            'password' => 'dpti@14234',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>true,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 15,
            'username' => 'dpsk',
            'password' => 'dpsk@15123',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 16,
            'username' => 'pmo',
            'password' => 'pmo@16765',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => true,
            'aset' => true,
            'finansial' => true,
            'hr'=>true,
            'sales'=>true,
            'legal'=>true,
            'progress'=>true,
            'pengadaan'=>true,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 17,
            'username' => 'ti',
            'password' => 'Nusantara@1',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => true,
            'aset' => true,
            'finansial' => true,
            'hr'=>true,
            'sales'=>true,
            'legal'=>true,
            'progress'=>true,
            'pengadaan'=>true,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 18,
            'username' => 'holding',
            'password' => 'Nusantara@1',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => false,
            'hr'=>true,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 19,
            'username' => 'pmn',
            'password' => 'pmn@19465',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 20,
            'username' => 'dspi',
            'password' => 'dspi@20768',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => true,
            'aset' => true,
            'finansial' => true,
            'hr'=>true,
            'sales'=>true,
            'legal'=>true,
            'progress'=>true,
            'pengadaan'=>true,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 21,
            'username' => 'dktb',
            'password' => 'dktb@21543',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>true,
            'sales'=>false,
            'legal'=>false,
            'progress'=>true,
            'pengadaan'=>false,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 22,
            'username' => 'dspr',
            'password' => 'dspr@22098',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>false,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 23,
            'username' => 'dipb',
            'password' => 'dipb@23768',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>false,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 24,
            'username' => 'dhkl',
            'password' => 'dhkl@24765',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>false,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 25,
            'username' => 'dosg',
            'password' => 'dosg@25765',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => true,
            'hr'=>true,
            'sales'=>false,
            'legal'=>false,
            'progress'=>false,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 26,
            'username' => 'direksi',
            'password' => 'direksiNusantara@1',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => true,
            'aset' => true,
            'finansial' => true,
            'hr'=>true,
            'sales'=>true,
            'legal'=>true,
            'progress'=>true,
            'pengadaan'=>true,
            'carbon'=>true,
            'warehouse'=>true
        ],
        [
            'id' => 27,
            'username' => 'dekom',
            'password' => 'Nusantara@1',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => false,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>false,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 28,
            'username' => 'pemasaran_holding',
            'password' => 'pemasaranhold@1',
            'mrc' => true,
            'gis' => true,
            'lm' => true,
            'aigr1' => true,
            'garda' => true,
            'operasional' => false,
            'aset' => false,
            'finansial' => false,
            'hr'=>false,
            'sales'=>true,
            'legal'=>false,
            'progress'=>false,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
        [
            'id' => 29,
            'username' => 'kaligua',
            'password' => 'Kaligua@1',
            'mrc' => false,
            'gis' => false,
            'lm' => false,
            'aigr1' => false,
            'garda' => false,
            'operasional' => false,
            'aset' => false,
            'finansial' => false,
            'hr'=>false,
            'sales'=>false,
            'legal'=>false,
            'progress'=>false,
            'pengadaan'=>false,
            'carbon'=>false,
            'warehouse'=>true
        ],
    ];

    public function retrieveById($identifier)
    {
        foreach ($this->users as $user) {
            if ($user['id'] == $identifier) {
                return new CustomUser($user);
            }
        }

        return null;
    }

    public function retrieveByToken($identifier, $token)
    {
        // Not implemented
    }

    public function updateRememberToken(UserContract $user, $token)
    {
        // Not implemented
    }

    public function retrieveByCredentials(array $credentials)
    {
        foreach ($this->users as $user) {
            if ($user['username'] == $credentials['username']) {
                return new CustomUser($user);
            }
        }

        return null;
    }

    public function validateCredentials(UserContract $user, array $credentials)
    {
        return $user->password === $credentials['password'];
    }
}